### ISSUE TITLE
Minor Currency

### ISSUE THREAD

**Issue by niccholaspage** [niccholaspage/Fe#4]
Add in a minor currency like dollars and cents.

**Comment by minecrafter** [comment]
I really don't want Fe to end up being another iConomy.

I would imagine if it had 2 currency modes (with default settings, plus a minor currency of Au, since Fe is a scientific name for iron):
- 30.6 Fe
- 30 Fe 6 Au

There would have to be more possibilities too... so should currency be a Phrase-formatted message? Not sure.

**Comment by niccholaspage** [comment]
I think I'm going to be keeping the default the way it is, so even after this commit it will still show up as 0.50 Fe or 4 Fe. I don't know if I'm going to have to edit phrases or not, I'll need to see.
